<a href="https://colab.research.google.com/github/Mike-Pits/CV/blob/main/10_%D0%94%D0%97_1_Python_%D0%B4%D0%BB%D1%8F_%D0%B0%D0%BD%D0%B0%D0%BB%D0%B8%D0%B7%D0%B0_%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D1%85_%7C_%D0%9F%D0%BE%D1%81%D1%82%D1%80%D0%BE%D0%B5%D0%BD%D0%B8%D0%B5_%D0%BA%D0%BE%D0%BD%D0%B2%D0%B5%D0%B9%D0%B5%D1%80%D0%B0_%D0%BE%D0%B1%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%BA%D0%B8_%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D1%85_%7C_%D0%94%D0%97_1_%7C_%D0%A3%D0%98%D0%98.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Все домашние задания по данному занятию будут построены на базе ```house_train.csv```, которая содержит цены на жилье и разные параметры этого жилья.

Полное описание признаков датасета:
    
* SalePrice: Цена продажи недвижимости в долларах. Это целевая переменная, которую нужно будет пытаться предсказать.
* MSSubClass: Класс здания
* MSZoning: Общая классификация зонирования
* LotFrontage: Погонные метры улицы соединенной с объектом
* LotArea: Размер лота в квардратных футах
* Street: Тип подъездной дороги
* Alley: Тип подъезда к аллее
* LotShape: Общий вид собственности
* LandContour: Плоскость собственности
* Utilities: Тип доступных коммунальных услуг
* LotConfig: Конфигурация лота
* LandSlope: Наклон собственности
* Neighborhood: Физические места в пределах города Эймс
* Condition1: Близость к главной дороге или железной дороге
* Condition2: Близость к главной дороге или железной дороге (если есть второй)
* BldgType: Тип объекта
* HouseStyle: Стиль объекта
* OverallQual: Общее качество материала и отделки
* OverallCond: Общий рейтинг состояния
* YearBuilt: Дата первоначального строительства
* YearRemodAdd: Дата переделки
* RoofStyle: Тип крыши
* RoofMatl: Материал крыши
* Exterior1st: Наружное покрытие дома
* Exterior2nd: Наружное покрытие дома (если больше одного материала)
* MasVnrType: Тип облицовки кладки
* MasVnrArea: Площадь облицовки каменной кладкой в квадратных футах
* ExterQual: Качество наружных материалов
* ExterCond: Текущее состояние материала снаружи
* Foundation: Тип фундамента
* BsmtQual: Высота подвала
* BsmtCond: Общее состояние подвала
* BsmtExposure: Стены подвала на уровне сада или выхода
* BsmtFinType1: Качество готовой площади подвала
* BsmtFinSF1: Готовые квадратные футы типа 1
* BsmtFinType2: Качество второй готовой площади (при наличии)
* BsmtFinSF2: Готовые квадратные футы типа 2
* BsmtUnfSF: Незаконченные квадратные метры подвального помещения
* TotalBsmtSF: Общая площадь подвала в квадратных футах
* Heating: Тип отопления
* HeatingQC: Качество и состояние отопления
* CentralAir: Центральное кондиционирование
* Electrical: Электрическая система
* 1stFlrSF: Квадратные футы первого этажа
* 2ndFlrSF: Квадратные метры второго этажа
* LowQualFinSF: Некачественная отделка квадратных футов (все этажи)
* GrLivArea: Надземная жилая площадь в квадратных футах
* BsmtFullBath: Ванная комната на цокольном этаже
* BsmtHalfBath: Полуподвальная ванная комната
* FullBath: Ванные комнаты высшего класса
* HalfBath: Полуванные комнаты высшего класса
* Bedroom: Количество спален над цокольным этажом
* Kitchen: Кол-во кухонь
* KitchenQual: Качество кухни
* TotRmsAbvGrd: Комнаты выше уровня (не включая ванные комнаты)
* Functional: Рейтинг функциональности дома
* Fireplaces: Количество каминов
* FireplaceQu: Качество камина
* GarageType: Расположение гаража
* GarageYrBlt: Год постройки гаража
* GarageFinish: Внутренняя отделка гаража
* GarageCars: Размер гаража для машины
* GarageArea: Размер гаража в квадратных футах
* GarageQual: Качество гаража
* GarageCond: Состояние гаража
* PavedDrive: Асфальтированная подъездная дорога
* WoodDeckSF: Площадь деревянной террасы в квадратных футах
* OpenPorchSF: Площадь открытой веранды в квадратных футах
* EnclosedPorch: Площадь закрытого крыльца в квадратных футах
* 3SsnPorch: Площадь крыльца на три сезона в квадратных футах
* ScreenPorch: Площадь крыльца экрана в квадратных футах
* PoolArea: Площадь бассейна в квадратных футах
* PoolQC: Качество бассейна
* Fence: Качество забора
* MiscFeature: Прочие функции, не включенные в другие категории
* MiscVal: Ценность разного свойства
* MoSold: Количество месяцев
* YrSold: Количество лет
* SaleType: Тип продажи
* SaleCondition: Состояние продажи

1. Загрузите данные датасета ```house_train.csv```. Импортируйте библиотеку Pandas и выведите на экран датасет в формате датафрейма.

In [142]:
# Библиотека для загрузки датасета из облака google
import gdown

# Запустите ячейку для загрузки датасета house_train.csv в директорию
url = 'https://storage.yandexcloud.net/aiueducation/Content/additional/pad/house_train.csv'
gdown.download(url, None, quiet=False)

Downloading...
From: https://storage.yandexcloud.net/aiueducation/Content/additional/pad/house_train.csv
To: /content/house_train.csv
100%|██████████| 461k/461k [00:00<00:00, 861kB/s]

'house_train.csv'

In [143]:
# Ваше решение
import pandas as pd
import numpy as np

In [144]:
data = pd.read_csv('house_train.csv')
data.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

2. Найдите признаки с пропусками. Если количество пропусков в признаке больше 50%, то удалите весь столбец признака. Если не более 50%, то пропуски замените на среднее значение в случае численного признака и на наиболее часто встречаемое значение в случае категориального.

In [145]:
# Назначим столбец Id индексом
data.index = data.Id
del data['Id']
data.head(10)

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
Id,,,,,,,,,,,,,,,,,,,,,
1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
6,50,RL,85.0,14115,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,NaN,MnPrv,Shed,700,10,2009,WD,Normal,143000
7,20,RL,75.0,10084,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,307000
8,60,RL,NaN,10382,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,NaN,NaN,Shed,350,11,2009,WD,Normal,200000
9,50,RM,51.0,6120,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,4,2008,WD,Abnorml,129900
10,190,RL,50.0,7420,Pave,NaN,Reg,Lvl,AllPub,Corner,...,0,NaN,NaN,NaN,0,1,2008,WD,Normal,118000

In [ ]:
# Заметим, что, например, столбец LotFrontage 8-я строка имеет пропуск

In [148]:
# Создадим списки с численными и категориальными признаками
numeric_cols = list(data.select_dtypes(include=np.number))
cat_cols = list(data.select_dtypes(exclude=np.number))

In [149]:
# Произвольно выберем признак и отметим кол-во отсутствующих полей
data['LotFrontage'].notnull().value_counts()

True     1201
False     259
Name: LotFrontage, dtype: int64

In [150]:
# Выявляем пропуски и выполняем с ними действия, согласно задания

for col in numeric_cols:
  if  (data[col].notnull().value_counts() / data.shape[0]).any() < 0.5:
    del data[col]
  else:
      data[col] = data[col].fillna(data[col].mean())

for col in cat_cols:
  if (data[col].notnull().sum() / data.shape[0]).any() < 0.5:
    del data[col]
  else:
    data[col] = data[col].fillna(data[col].value_counts().idxmax())

In [156]:
# Проверка столбца LotFrontage 8-я строка
data.head(10)

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
Id,,,,,,,,,,,,,,,,,,,,,
1,60,RL,65.000000,8450,Pave,Grvl,Reg,Lvl,AllPub,Inside,...,0,Gd,MnPrv,Shed,0,2,2008,WD,Normal,208500
2,20,RL,80.000000,9600,Pave,Grvl,Reg,Lvl,AllPub,FR2,...,0,Gd,MnPrv,Shed,0,5,2007,WD,Normal,181500
3,60,RL,68.000000,11250,Pave,Grvl,IR1,Lvl,AllPub,Inside,...,0,Gd,MnPrv,Shed,0,9,2008,WD,Normal,223500
4,70,RL,60.000000,9550,Pave,Grvl,IR1,Lvl,AllPub,Corner,...,0,Gd,MnPrv,Shed,0,2,2006,WD,Abnorml,140000
5,60,RL,84.000000,14260,Pave,Grvl,IR1,Lvl,AllPub,FR2,...,0,Gd,MnPrv,Shed,0,12,2008,WD,Normal,250000
6,50,RL,85.000000,14115,Pave,Grvl,IR1,Lvl,AllPub,Inside,...,0,Gd,MnPrv,Shed,700,10,2009,WD,Normal,143000
7,20,RL,75.000000,10084,Pave,Grvl,Reg,Lvl,AllPub,Inside,...,0,Gd,MnPrv,Shed,0,8,2007,WD,Normal,307000
8,60,RL,70.049958,10382,Pave,Grvl,IR1,Lvl,AllPub,Corner,...,0,Gd,MnPrv,Shed,350,11,2009,WD,Normal,200000
9,50,RM,51.000000,6120,Pave,Grvl,Reg,Lvl,AllPub,Inside,...,0,Gd,MnPrv,Shed,0,4,2008,WD,Abnorml,129900
10,190,RL,50.000000,7420,Pave,Grvl,Reg,Lvl,AllPub,Corner,...,0,Gd,MnPrv,Shed,0,1,2008,WD,Normal,118000

In [155]:
# Заметим, что числове поле в столбце LotFrontage и строке 8 заменено на среднее
# Также проверим пару признаков на наличие пропусков после обработки дата-фрейма
data['RoofStyle'].isna().sum()

0

In [157]:
data['LotFrontage'].notnull().value_counts()

True    1460
Name: LotFrontage, dtype: int64

In [153]:
# Задание выполнено